---
name: Annotation
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda:bioconductor-delayedarray=0.12.0
  - bioconda:bioconductor-deseq2=1.26.0
  - conda-forge:r-readr=1.3.1
  - bioconda:bioconductor-summarizedexperiment=1.16.0
  - bioconda:bioconductor-iranges=2.20.0
