fasta: /mnt/beegfs/database/bioinfo/nf-core-chipseq/1.2.2/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa
gtf: /mnt/beegfs/database/bioinfo/nf-core-chipseq/1.2.2/Homo_sapiens/NCBI/GRCh38/Annotation/Genes/genes.gtf
bwa_index: /mnt/beegfs/database/bioinfo/nf-core-chipseq/1.2.2/Homo_sapiens/NCBI/GRCh38/Sequence/BWAIndex/genome.fa
gene_bed:
blacklist:
igenomes_base: /mnt/beegfs/database/bioinfo/nf-core-chipseq/1.2.2/

macs_gsize:

