max_threads: 20

ref:
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Bismark/GRCh38/GRCh38.99.homo_sapiens.dna.main_chr.fasta
  bismark_index: /mnt/beegfs/database/bioinfo/Index_DB/Bismark/GRCh38/Bisulfite_Genome
  bismark_frequencies: /mnt/beegfs/database/bioinfo/Index_DB/Bismark/GRCh38/genomic_nucleotide_frequencies.txt

bismark:
  mapping_extra: --fastq --bam --phred33-quals --ambiguous --unmapped --nucleotide_coverage
  extract: --gzip --comprehensive --bedGraph
  skip_optional_reports: false

fastp:
  fastp_adapters: null
  fastp_extra: ""

bismark:
  mapping_extra: --fastq --bam --phred33-quals --ambiguous --unmapped --nucleotide_coverage
  extract: --gzip --comprehensive --bedGraph
  skip_optional_reports: false