design: design.tsv
snpeff_snpsift:
  snpeff_extra: -noLog -nodownload -lof
  snpsift_kaviar: -name 'Kaviar_' -exists 'ExistsInKaviar' -tabix -noDownload -noLog
  snpsift_cosmic: -name 'cosmic_' -exists 'ExistsInCosmic' -tabix -noDownload -noLog
  snpsift_dbsnp: -name 'dbSNP_' -exists 'ExistsInDBsnp' -tabix -noDownload -noLog
  snpsift_clinvar: -name 'clinvar_' -exists 'ExistsInClinVar' -tabix -noDownload -noLog
  snpsift_gnomad: -name 'gnomAD_genomes_' -exists 'ExistsInGnomAD' -tabix -noDownload -noLog
  snpsift_exac: -name 'gnomAD_exomes_' -exists 'ExistsInExac' -tabix -noDownload -noLog
  snpsift_dbvar: -name 'dbVar_' -exists 'ExistsInDbVar' -tabix -noDownload -noLog
  snpsift_dbnsfp: -noDownload -noLog -f 'hg18_chr,hg18_pos(1-based)' -n -g hg38
  snpsift_gwascat: -g hg38 -noDownload -noLog
params:
  center: GustaveRoussy
  ncbi_build: GRCh38
  chr:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
    - "13"
    - "14"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - X
    - Y
    - MT
ref:
  cosmic: /mnt/beegfs/database/bioinfo/COSMIC/73_20150629/CosmicCodingMuts.ucsc.nochr.vcf.gz
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/dbSNP/GRCh38p7/All_20180418.nochr.vcf.gz
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.fasta
  gmt: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/GeneSets.gmt
  gwascat: /mnt/beegfs/database/bioinfo/Index_DB/GWASCatalog/gwas_catalog_v1.0.2-studies_r2020-05-03.tsv
  kaviar: /mnt/beegfs/database/bioinfo/Index_DB/Kaviar/HG38/Kaviar-160204-Public/vcfs/Kaviar-160204-Public-hg38-trim.vcf.gz
  snpeff: /mnt/beegfs/database/bioinfo/Index_DB/SnpEff/GRCh38.86
  capture_kit_bed: /mnt/beegfs/database/bioinfo/Index_DB/captureKitDesigns/hg38/v5/sureselect_v5.padded.nochr.bed
  af_only: /mnt/beegfs/database/bioinfo/Index_DB/GATK/mutect2_gnomad_af_only/hg38/somatic-hg38_af-only-gnomad.hg38.nochr.vcf.gz
  dbnsfp: /mnt/beegfs/database/bioinfo/Index_DB/dbNSFP/4.1/GRCh38/dbNSFP4.1a.txt.gz
  gnomad: /mnt/beegfs/database/bioinfo/Index_DB/gnomad/gnomad.genomes.r3.0.sites.vcf.nochr.bgz
  exac: /mnt/beegfs/database/bioinfo/Index_DB/Exac/release1/ExAC.r1.sites.vep.vcf.gz
  clinvar: /mnt/beegfs/database/bioinfo/Index_DB/ClinVar/GRCh38/clinvar_20210102.vcf.gz
  oncokb: /mnt/beegfs/database/bioinfo/Index_DB/OncoKB/OncoKB.csv
  dbvar: /mnt/beegfs/database/bioinfo/Index_DB/dbVar/GRCh38.variant_call.all.vcf.gz
  cancer_census: /mnt/beegfs/database/bioinfo/Index_DB/CancerGeneCensus/Census_allTue_Aug_31_15_11_39_2021.csv
  mane: /mnt/beegfs/database/bioinfo/Index_DB/MANE/MANE_human/release_0.95/MANE.GRCh38.v0.95.summary.txt.gz
  revel: /mnt/beegfs/database/bioinfo/Index_DB/REVEL/revel_with_transcript_ids
  mistic: /mnt/beegfs/database/bioinfo/Index_DB/MISTIC/MISTIC_GRCh38.tsv.gz
threads: 20
