restart-times: 1
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
cluster-cancel: "scancel"
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 2
jobs: 300
keep-going: true
reason: true
printshellcmds: true
jobname: "{name}.{jobid}.demux.snakejob.sh"
conda-prefix: /mnt/beegfs/pipelines/unofficial-snakemake-wrappers/shared_install/
singularity-prefix: /mnt/beegfs/pipelines/unofficial-snakemake-wrappers/singularity/
wrapper-prefix: file:///mnt/beegfs/pipelines/snakemake-wrappers/
use-singularity: true
use-conda: true
shadow-prefix: tmp/shadow
rerun-triggers: mtime
# log-handler-script: "log_handler.py"