channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bioconductor-clusterprofiler =4.2
  - r-cairo =1.6_0
  - r-upsetr =1.4
  - bioconductor-do.db =2.9=r41hdfd78af_13
  - r-ggupset =0.3
  - r-europepmc =0.4