steps:
  cutntag: false
  chipseq: false
  atac: false

reference:
  genome: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta
  genome_index: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.fai
  genome_dict: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.dict
  blacklist: /mnt/beegfs/database/bioinfo/Index_DB/blacklist/hg38.blacklist.merged.bed

bowtie2:
  index: /mnt/beegfs/database/bioinfo/Index_DB/Bowtie/2.4/GRCh38
  index_prefix: /mnt/beegfs/database/bioinfo/Index_DB/Bowtie/2.4/GRCh38/GRCh38.99

fastp:
  adapters: null