reference:
  genome: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.dna.fasta
  genome_index: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.dna.fasta.fai
  genome_dict: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCm38.99/GRCm38.99.mus_musculus.dna.dict
  blacklist: /mnt/beegfs/database/bioinfo/Index_DB/blacklist/mm10.blacklist.merged.bed

bowtie2:
  index: /mnt/beegfs/database/bioinfo/Index_DB/Bowtie/2.4/GRCm38

fastp:
  adapters: null