restart-times: 1
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
cluster-sidecar: "slurm-sidecar.py"
cluster-cancel: "scancel"
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 2
jobs: 30
keep-going: true
reason: true
printshellcmds: true
jobname: "{name}.{jobid}.slurm.snakejob.sh"
conda-prefix: /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/conda
# singularity-prefix: /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/singularity
wrapper-prefix: file:///mnt/beegfs/pipelines/snakemake-wrappers/
# use-singularity: true
use-conda: true
shadow-prefix: tmp/shadow
rerun-triggers: mtime