max_threads: 20

table_cols:
- CHROM
- POS
- ID
- REF
- ALT
- FILTER
- ANN[*].EFFECT
- ANN[*].IMPACT
- ANN[*].GENE
- DP
- ANN[*].GENEID
- ANN[*].BIOTYPE
- ANN[*].HGVS_C
- ANN[*].HGVS_P
- ANN[*].CDNA_POS
- ANN[*].CDS_POS
- dbNSFP_gnomAD_exomes_AC
- dbNSFP_gnomAD_exomes_AF
- gnomad_AC
- gnomad_AF
- dbNSFP_1000Gp3_AC
- dbNSFP_1000Gp3_AF
- dbNSFP_ExAC_AC
- dbNSFP_ExAC_AF
- dbNSFP_FATHMM_pred
- dbNSFP_FATHMM_score
- Kaviar_AC
- Kaviar_AF
- OncoKB_Is_Oncogene
- OncoKB_Is_Tumor_Suppressor_Gene
- OncoKB_MSK_HEME
- OncoKB_MSK_IMPACT
- MISTIC_pred
- MISTIC_score
- dbNSFP_SIFT4G_pred
- dbNSFP_SIFT4G_score
- CancerGeneCensus_Cancer_Syndrome
- CancerGeneCensus_Chr_Band
- CancerGeneCensus_Hallmark
- CancerGeneCensus_Molecular_Genetics
- CancerGeneCensus_Mutation_Types
- CancerGeneCensus_Other_Syndrome
- CancerGeneCensus_Role_in_Cancer
- CancerGeneCensus_Somatic
- CancerGeneCensus_Synonyms
- CancerGeneCensus_Tier
- CancerGeneCensus_Tissue_Type
- CancerGeneCensus_Translocation_Partner
- CancerGeneCensus_Tumour_TypesGermline
- CancerGeneCensus_Tumour_TypesSomatic
- LOF[*].GENE
- LOF[*].GENEID
- LOF[*].NUMTR
- LOF[*].PERC

reference:
  ncbi_build: GRCh38
  fasta: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.fasta
  fasta_index: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.fasta.fai
  fasta_dict: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.99/GRCh38.99.homo_sapiens.dna.main_chr.dict
  capture_kit_bed: /mnt/beegfs/database/bioinfo/Index_DB/captureKitDesigns/hg38/v5/sureselect_v5.padded.nochr.bed
  af_only: /mnt/beegfs/database/bioinfo/Index_DB/GATK/mutect2_gnomad_af_only/hg38/somatic-hg38_af-only-gnomad.hg38.nochr.vcf.gz
  af_only_tbi: /mnt/beegfs/database/bioinfo/Index_DB/GATK/mutect2_gnomad_af_only/hg38/somatic-hg38_af-only-gnomad.hg38.nochr.vcf.gz.tbi
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/dbSNP/GRCh38p7/All_20180418.nochr.vcf.gz
  dbsnp_tbi: /mnt/beegfs/database/bioinfo/Index_DB/dbSNP/GRCh38p7/All_20180418.nochr.vcf.gz.tbi
  snpeff: /mnt/beegfs/database/bioinfo/Index_DB/SnpEff/GRCh38.86
  gmt: /mnt/beegfs/database/bioinfo/Index_DB/MSigDB/GeneSets.gmt
  kaviar: /mnt/beegfs/database/bioinfo/Index_DB/Kaviar/HG38/Kaviar-160204-Public/vcfs/Kaviar-160204-Public-hg38-trim.vcf.gz
  kaviar_tbi: /mnt/beegfs/database/bioinfo/Index_DB/Kaviar/HG38/Kaviar-160204-Public/vcfs/Kaviar-160204-Public-hg38-trim.vcf.gz.tbi
  cosmic: /mnt/beegfs/database/bioinfo/COSMIC/73_20150629/CosmicCodingMuts.ucsc.nochr.vcf.gz
  cosmic_tbi: /mnt/beegfs/database/bioinfo/COSMIC/73_20150629/CosmicCodingMuts.ucsc.nochr.vcf.gz.tbi
  dbnsfp: /mnt/beegfs/database/bioinfo/Index_DB/dbNSFP/4.1/GRCh38/dbNSFP4.1a.txt.gz
  clinvar: /mnt/beegfs/database/bioinfo/Index_DB/ClinVar/GRCh38/clinvar_20210404.vcf.gz
  clinvar_tbi: /mnt/beegfs/database/bioinfo/Index_DB/ClinVar/GRCh38/clinvar_20210404.vcf.gz.tbi
  gnomad: /mnt/beegfs/database/bioinfo/Index_DB/gnomad/gnomad.genomes.r3.0.sites.vcf.nochr.bgz
  gnomad_tbi: /mnt/beegfs/database/bioinfo/Index_DB/gnomad/gnomad.genomes.r3.0.sites.vcf.nochr.bgz.tbi
  exac: /mnt/beegfs/database/bioinfo/Index_DB/Exac/release1/ExAC.r1.sites.vep.fixed.vcf.gz
  exac_tbi: /mnt/beegfs/database/bioinfo/Index_DB/Exac/release1/ExAC.r1.sites.vep.fixed.vcf.gz.tbi
  dbvar: /mnt/beegfs/database/bioinfo/Index_DB/dbVar/GRCh38.variant_call.all.vcf.gz
  dbvar_tbi: /mnt/beegfs/database/bioinfo/Index_DB/dbVar/GRCh38.variant_call.all.vcf.gz.tbi
  gwascat: /mnt/beegfs/database/bioinfo/Index_DB/GWASCatalog/gwas_catalog_v1.0.2-studies_r2020-05-03.tsv
  mane: /mnt/beegfs/database/bioinfo/Index_DB/MANE/MANE_human/release_0.95/MANE.GRCh38.v0.95.summary.txt.gz
  revel: /mnt/beegfs/database/bioinfo/Index_DB/REVEL/revel_with_transcript_ids
  mistic: /mnt/beegfs/database/bioinfo/Index_DB/MISTIC/MISTIC_GRCh38.tsv.gz
  cancer_census: /mnt/beegfs/database/bioinfo/Index_DB/CancerGeneCensus/Census_allTue_Aug_31_15_11_39_2021.csv
  oncokb: /mnt/beegfs/database/bioinfo/Index_DB/OncoKB/OncoKB.csv
  bwa_index: 
    - /mnt/beegfs/database/bioinfo/Index_DB/BWA/2.2.1/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.0123
    - /mnt/beegfs/database/bioinfo/Index_DB/BWA/2.2.1/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.amb
    - /mnt/beegfs/database/bioinfo/Index_DB/BWA/2.2.1/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.ann
    - /mnt/beegfs/database/bioinfo/Index_DB/BWA/2.2.1/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.bwt.2bit.64
    - /mnt/beegfs/database/bioinfo/Index_DB/BWA/2.2.1/GRCh38.99/GRCh38.99.homo_sapiens.dna.fasta.pac
  msi_scan: /mnt/beegfs/database/bioinfo/Index_DB/MSI/GRCh38.99/GRCh38.99.msi.list
  chr:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
    - "13"
    - "14"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - X
    - Y
    - MT


fastp:
  fastp_adapters: null
  fastp_extra: ""


samtools:
  fixmate_extra: -cmr
  view_filter: -h -q 5
  stats: ""


sambamba:
  index_extra: ""
  sort_extra: ""
  markdup_extra: --remove-duplicates



gatk:
  apply_base_recal: --create-output-bam-index
  base_recalibrator: ""
  mutect2_extra: --create-output-variant-index --max-reads-per-alignment-start 0 --disable-read-filter MateOnSameContigOrNoMappedMateReadFilter --annotation AlleleFraction --annotation AllelePseudoDepth --annotation --annotation AS_BaseQualityRankSumTest --annotation AS_FisherStrand --annotation AS_InbreedingCoeff --annotation --annotation AS_MappingQualityRankSumTest --annotation AS_QualByDepth --annotation AS_ReadPosRankSumTest --annotation AS_RMSMappingQuality --annotation --annotation AS_StrandBiasMutectAnnotation --annotation AS_StrandOddsRatio --annotation AssemblyComplexity --annotation BaseQuality --annotation --annotation BaseQualityHistogram --annotation BaseQualityRankSumTest --annotation ChromosomeCounts --annotation ClippingRankSumTest --annotation --annotation CountNs --annotation Coverage --annotation DepthPerAlleleBySample --annotation DepthPerSampleHC --annotation ExcessHet --annotation --annotation FeaturizedReadSets --annotation FisherStrand --annotation FragmentDepthPerAlleleBySample --annotation FragmentLength --annotation --annotation GenotypeSummaries --annotation InbreedingCoeff --annotation LikelihoodRankSumTest --annotation MappingQuality --annotation --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation OrientationBiasReadCounts --annotation --annotation OriginalAlignment --annotation PossibleDeNovo --annotation QualByDepth --annotation ReadPosition --annotation ReadPosRankSumTest --annotation --annotation ReferenceBases --annotation RMSMappingQuality --annotation SampleList --annotation StrandBiasBySample --annotation StrandOddsRatio --annotation --annotation TandemRepeat --annotation UniqueAltReadCountPossible
  learn_read_orientation_model: ""
  get_pileup_summaries: ""
  calculate_contamination: ""
  filter_mutect_calls: --create-output-variant-index --min-median-mapping-quality 35
  gatk_filters:
    DepthBelow10X: "DP < 10"
    BelowQualByDepth: "QD <= 2.0"
    BelowBaseQuality: "QUAL < 30.0"
    AboveFisherStrandBias: "FS > 60.0"
    AboveStrandOddsRatio: "SOR > 3.0"
    BelowMappingQuality: "MQ < 35.0"
    BelowMQRankSum: "MQRankSum < -12.5"
    BelowReadPosRankSum: "ReadPosRankSum < -8.0"


bcftools:
  split_multiallelic: -m -both --check-ref w


snpeff:
  extra: -nodownload -noLog


snpsift:
  dbsnp: -name 'dbSNP_' -tabix -noDownload -noLog
  kaviar: -name 'Kaviar_' -tabix -noDownload -noLog
  cosmic: -name 'cosmic_' -tabix -noDownload -noLog
  dbnsfp: -noDownload -noLog -n -f 'hg18_chr,hg18_pos(1-based)'
  clinvar: -name 'clinvar_' -tabix -noDownload -noLog
  gnomad: -name 'gnomad_' -tabix -noDownload -noLog
  exac: -name 'gnomAD_exomes_' -tabix -noDownload -noLog
  dbvar: -name 'dbVar_' -tabix -noDownload -noLog
  extract_all_fields: -s ';' -e '.'


bigr_additionals:
  remove_non_conventional_chromosomes: true
  format_to_info: ""


vcftools:
  mane: --columns INFO/MANE_NCBI_GeneID,INFO/MANE_Ensembl_Gene,INFO/MANE_HGNC_ID,INFO/MANE_symbol,INFO/MANE_name,INFO/MANE_RefSeq_nuc,INFO/MANE_RefSeq_prot,INFO/MANE_Ensembl_nuc,INFO/MANE_Ensembl_prot,INFO/MANE_MANE_status,CHROM,FROM,TO,INFO/MANE_chr_strand
  revel: --columns CHROM,POS,-,REF,ALT,INFO/REVEL_aaref,INFO/REVEL_aaalt,INFO/REVEL,INFO/REVEL_Ensembl_transcriptid
  mistic: --columns CHROM,POS,REF,ALT,INFO/MISTIC_score,INFO/MISTIC_pred


cnv_facets:
  extra: --snp-count-orphans --gbuild hg38 --nbhd-snp 250


msisensor:
  extra: ""
  stability_threshold: 3.5


annot_sv:
  install_dir: /mnt/beegfs/pipelines/snakemake-wrappers/bigr_pipelines/annot_sv/source/AnnotSV/
  extra: -annotationMode both -snvIndelPASS 1 -tx ENSEMBL -SVinputInfo 0


tmb:
  min_coverage: 10
  tmb_highness_threshold: 10
  allele_depth_keyname: AD


star_fusion:
  CTAT_resource_lib: /mnt/beegfs/database/bioinfo/Index_DB/CTAT_Resource_Lib/GRCh38_gencode_v37/GRCh38_gencode_v37_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir/
  extra: --FusionInspector inspect


star:
  index: /mnt/beegfs/database/bioinfo/Index_DB/STAR/GRCh38
  chimera_extra: --outSAMtype BAM Unsorted --outReadsUnmapped None --twopassMode Basic --outSAMstrandField intronMotif --outSAMunmapped Within --chimSegmentMin 12 --chimJunctionOverhangMin 8 --chimOutJunctionFormat 1 --alignSJDBoverhangMin 10 --alignMatesGapMax 100000 --alignIntronMax 100000 --alignSJstitchMismatchNmax 5 -1 5 5 --outSAMattributes Standard --chimMultimapScoreRange 3 --chimScoreJunctionNonGTAG -4 --chimMultimapNmax 20 --chimNonchimScoreDropMin 10 --peOverlapNbasesMin 12 --peOverlapMMp 0.1 --alignInsertionFlush Right --alignSplicedMateMapLminOverLmate 0 --alignSplicedMateMapLmin 30



fastq_screen:
  database:
    Contaminants:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Adapters/Contaminants
    AThaliana:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Arabidopsis/Arabidopsis_thaliana.TAIR10
    Drosophila:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Drosophila/BDGP6
    Ecoli:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/E_coli/Ecoli
    Human:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Human/Homo_sapiens.GRCh38
    Lambda:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Lambda/Lambda
    Mitochondria:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mitochondria/mitochondria
    Mouse:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Mouse/Mus_musculus.GRCm38
    PhiX:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/PhiX/phi_plus_SNPs
    Rat:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Rat/Rnor_6.0
    rRNA:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/rRNA/GRCm38_rRNA
    Vectors:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Vectors/Vectors
    Worm:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Worm/Caenorhabditis_elegans.WBcel235
    Yeast:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/Yeast/Saccharomyces_cerevisiae.R64-1-1
    SalmoSalar:
      bowtie2: /mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.14.0/SalmoSalar/Salmo_salar.ICSASG_v2
  aligner_paths:
    bowtie2: bowtie2
